name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: Acrolinx.Demo.Sidebar.Net.sln
      NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mkdir download
        run: mkdir download

      - name: download sonar
        run: powershell Invoke-WebRequest -Uri "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.13.0.66756/sonar-scanner-msbuild-5.13.0.66756-net46.zip" -OutFile "download\sonarmsbuild.zip"

      - name: extract sonar
        run: powershell Expand-Archive download\sonarmsbuild.zip sonar-msbuild\

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Nuget restore
        uses: nuget/setup-nuget@v2
      - run: nuget restore $env:Solution_Name

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Java - required by sonar
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set version from tag name
        if: startsWith(github.ref,'refs/tags/v')
        shell: powershell
        run: patch-assembly.ps1

      - name: begin sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: sonar-msbuild\SonarScanner.MSBuild.exe begin /o:"acrolinx" /k:"acrolinx_acrolinx-sidebar-demo-dotnet" /d:sonar.token=$env:SONAR_TOKEN /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

      - name: Build the application
        run: msbuild $env:Solution_Name /p:Configuration=Release

      - name: end sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: sonar-msbuild\SonarScanner.MSBuild.exe end /d:sonar.token=$env:SONAR_TOKEN
